# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 584cdef4897e0cada2f76c5f823b5176fba76314e86f47a1d5a5318ac8b60911479860d94d5a3add6a1eb8e7acf22993f780312337d29cd8208682c7ab812d5e

test:
  secret_key_base: 6b7be9bbe99b2461b902d50e5a8e0346f4e528a389da8c1edcfdde257df4d073d12692ef64f0bb97eb23688609d5591eb6e50b7150fc15ef3f3df9e0a07f62e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
